"""
MaixCAM / K230 Documentation Scraper using Firecrawl

This script uses the Firecrawl API to crawl MaixCAM and K230 documentation
and saves the results as markdown files for offline reference and API mapping.

Usage:
    export FIRECRAWL_API_KEY=your_api_key_here
    python scrape_maix_docs.py
"""

import os
import json
from pathlib import Path
from dotenv import load_dotenv
from firecrawl import FirecrawlApp

load_dotenv()

FIRECRAWL_API_KEY = os.getenv("FIRECRAWL_API_KEY")

DOCS_TARGETS = [
    {
        "name": "maix_camera",
        "url": "https://wiki.sipeed.com/maixpy/doc/zh/modules/camera.html",
        "description": "MaixCAM Camera API",
    },
    {
        "name": "maix_display",
        "url": "https://wiki.sipeed.com/maixpy/doc/zh/modules/display.html",
        "description": "MaixCAM Display API",
    },
    {
        "name": "maix_image",
        "url": "https://wiki.sipeed.com/maixpy/doc/zh/modules/image.html",
        "description": "MaixCAM Image API",
    },
    {
        "name": "maix_uart",
        "url": "https://wiki.sipeed.com/maixpy/doc/zh/modules/uart.html",
        "description": "MaixCAM UART API",
    },
]

OUTPUT_DIR = Path("docs")


def scrape_docs(app: FirecrawlApp, target: dict) -> str | None:
    """Scrape a single documentation URL and return the markdown content."""
    print(f"Scraping: {target['description']} ({target['url']})")
    try:
        result = app.scrape_url(
            target["url"],
            params={"formats": ["markdown"]},
        )
        if result and result.get("markdown"):
            return result["markdown"]
        print(f"  Warning: No markdown content returned for {target['name']}")
        return None
    except Exception as e:
        print(f"  Error scraping {target['url']}: {e}")
        return None


def save_markdown(name: str, description: str, content: str) -> Path:
    """Save scraped markdown content to a file."""
    OUTPUT_DIR.mkdir(exist_ok=True)
    output_path = OUTPUT_DIR / f"{name}.md"
    header = f"# {description}\n\n> Auto-generated by scrape_maix_docs.py\n\n"
    output_path.write_text(header + content, encoding="utf-8")
    print(f"  Saved: {output_path}")
    return output_path


def save_index(results: list[dict]) -> None:
    """Save a JSON index of all scraped documents."""
    OUTPUT_DIR.mkdir(exist_ok=True)
    index_path = OUTPUT_DIR / "index.json"
    index_path.write_text(
        json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"Index saved: {index_path}")


def main() -> None:
    if not FIRECRAWL_API_KEY:
        raise SystemExit(
            "Error: FIRECRAWL_API_KEY environment variable is not set.\n"
            "Set it with: export FIRECRAWL_API_KEY=your_api_key_here"
        )

    app = FirecrawlApp(api_key=FIRECRAWL_API_KEY)

    results = []
    for target in DOCS_TARGETS:
        content = scrape_docs(app, target)
        if content:
            output_path = save_markdown(target["name"], target["description"], content)
            results.append(
                {
                    "name": target["name"],
                    "description": target["description"],
                    "url": target["url"],
                    "file": str(output_path),
                    "status": "success",
                }
            )
        else:
            results.append(
                {
                    "name": target["name"],
                    "description": target["description"],
                    "url": target["url"],
                    "file": None,
                    "status": "failed",
                }
            )

    save_index(results)

    success = sum(1 for r in results if r["status"] == "success")
    print(f"\nDone: {success}/{len(results)} documents scraped successfully.")


if __name__ == "__main__":
    main()
